//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeDom.Generated
{
    using System;


    public class Squirrel
    {

        private string name = "Chip";

        public virtual string Name
        {
            get
            {
                return this.name;
            }
        }

        public virtual void SayHello(string greetee)
        {
            Console.WriteLine($"Squirrel named '{Name}' is greeting '{greetee}'");
        }
    }
}